name = "VisClaw"
uuid = "d5c85fe6-8620-4d3a-96f0-ac478d4f5d38"
authors = ["Takuya Miyashita <miyashita@hydrocoast.jp>"]
version = "0.3.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GMT = "5752ebe1-31b9-557e-87aa-f909b540aa54"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
GeometricalPredicates = "fd0ad045-b25c-564e-8f9c-8ef5c5f21267"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
GMT = "0.17, 0.18, 0.19"
GR = "0.48, 0.49"
GeometricalPredicates = "0.4"
Interpolations = "0.12"
Plots = "1.1, 1.2, 1.3"
julia = "1.3, 1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
